controlCeti/urls.py
from django.contrib import admin
from django.urls import path
from horario_sala import views

urlpatterns = [
    path('', views.IndexHorarioSala.as_view(), name='index'),  # Acá
    path('admin/', admin.site.urls),
    path('horariosala/', views.IndexHorarioSala.as_view(), name='index'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('create/', views.create_asistencia, name='create_asistencia'),
    path('edit/<int:id>', views.edit_asistencia, name='edit_asistencia'),
    path('update/<int:id>', views.update_asistencia, name='update_asistencia'),
    path('delete/<int:id>/', views.delete_asistencia, name='delete_asistencia')
]

horario_sala/models.py
from django.db import models

# Create your models here.
class HoraSala(models.Model):
    #EN AUNTOMATICO GENERA UN id AUTOINCREMENTABLE Y ENTERO
    matricula = models.TextField("Matrícula del Alumno", max_length=50, blank=True)
    nombre = models.TextField("Nombre del Alumno", max_length=50, blank=True)
    sala = models.CharField(" Nombre de la sala", max_length=50, blank=True)
    hora = models.CharField("Hora Alumno", max_length=50, blank=True)

    def __str__(self):
        return self.nombre
        

horario_sala/views.py
from django.shortcuts import render, redirect
from horario_sala.foms import HorarioSalaForm
from horario_sala.models import HoraSala
from django.views.generic import ListView


# Create your views here.
class IndexHorarioSala(ListView):
    template_name = 'index.html'
    context_object_name = 'lista_horarios_sala'

    def  get_queryset(self):
        return HoraSala.objects.all()


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')
        
def create_asistencia(request):
    if request.method == 'POST':
        form = HorarioSalaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    form = HorarioSalaForm()
    return render(request, 'create.html', {'form':form})  

def delete_asistencia(request, id):
    horario = HoraSala.objects.get(id = id)
    horario.delete()
    return redirect('index')

def edit_asistencia(request , id):
    horario = HoraSala.objects.get( id=id)
    return render(request, 'edit.html' , {'horario' :horario})

def update_asistencia (request , id):
    horario = HoraSala.objects.get( id=id)
    form = HorarioSalaForm(request.POST, instance = horario)
    if form.is_valid():
        form.save()
        return redirect( "index" )
    return render(request, 'edit.html' , {'horario' : horario})


            

horario_sala/templates/about.html
{% extends "side_up.html" %}

{% block content %}

<div class="container py-4">
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">Acerca de</h1>
            <p class="col-md-8 fs-4">Aplicación para llevar un registro de las asistencias en sala de computo en el
                CETI.</p>
            <p style="text-align: justify;">El Laboratorio de Informática es un espacio físico de 8.00 x 12.00 mts.,
                adaptado con equipo de cómputo, periféricos, equipo de medición, software, manuales y mobiliario
                dispuesto para ofrecer a los alumnos y profesores de la Licenciatura en Informática, las herramientas
                necesarias que facilitan el desarrollo de prácticas en las asignaturas del Plan de Estudios que así lo
                requieren. Además, se proporciona equipo y software a los Profesores-Investigadores que participan en
                los diversos cuerpos académicos para el desarrollo de sus proyectos de Investigación.

                El área de Sistemas Digitales del Laboratorio de Informática tiene una distribución física de 8.00 x
                6.00 mts. Aquí se encuentran ubicados el equipo de cómputo, equipo de medición, software y mobiliario
                para materias de las áreas de conocimiento de Arquitectura de Computadoras y Redes. Además este espacio
                es utilizado para llevar a cabo talleres que se imparten durante el verano a la comunidad universitaria
                interesada, tales como el Taller de Mantenimiento Preventivo y Correctivo de Equipo de Cómputo.

                Por su parte, el área de Ingeniería de Software cuenta con un espacio de 8.00 x 6.00 mts. En esta área
                se encuentra el equipo de cómputo, software, periféricos y mobiliario que se utilizan en las prácticas
                relacionadas con materias de las áreas de conocimiento de Tratamiento de Información, Interacción
                Humano-Computadora, Software Base y Programación e Ingeniería de Software.</p>
            <!-- <button class="btn btn-primary btn-lg" type="button">Example button</button> -->
        </div>
    </div>

    <div class="row align-items-md-stretch">
        <div class="col-md-6">
            <div class="h-100 p-5 text-white  rounded-3" style="background-color:#B22222;">
                <h2>CETI</h2>
                <p>Centro de Tecnologías de la información</p>
                <a class="btn btn-outline-secondary" href="{% url 'index' %}"> Listar Alumnos</a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="h-100 p-5 bg-light border rounded-3">
                <h2>Ver lista de alumnos</h2>
                <p>La aplicación se encarga de llevar un registro de los alumnos, horarios, además de tomar asistencia.
                </p>
                <a class="btn btn-outline-secondary" href="{% url 'index' %}"> Listar Alumnos</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

horario_sala/templates/copia.html
<!-- {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TecInfoII</title>

    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    {# Cargamos la librería #}
    {% load bootstrap4 %}

    {# CSS Bootstrap #}
    {% bootstrap_css %}

</head>

<body id="page-top">

    <div id="wrapper">


        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">INFORMÁTICA</div>
            </a>


            <hr class="sidebar-divider my-0">

           
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>TecInfo<sup>2</sup></span></a>
            </li>


            <hr class="sidebar-divider">

 
            <div class="sidebar-heading">
                DJANGO WITH MYSQL
            </div>

            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create_asistencia' %}">
                    <i class="fas fa-fw fa-check-circle"></i>
                    <span>Create</span></a>
            </li>

         
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">
                    <i class="fas fa-fw fa-bars"></i>
                    <span>Read</span></a>
            </li>
        </ul>
        
        <div id="content-wrapper" class="d-flex flex-column">

            
            <div id="content"> -->
                {% include side_up.html %}
                <h1>Tabla de contenido</h1>
                
                <table border="1" class="table table-striped">
                    <tr>
                        <th>Id</th>
                        <th>Matícula </th>
                        <th>Nombre </th>
                        <th>Sala </th>
                        <th>Hora </th>
                        <th>Update </th>
                        <th>Delete </th>
                    </tr>
                    <tbody>
                        {% for horario in lista_horarios_sala %}
                        <tr>
                            <td>{{horario.id}} </td>
                            <td>{{horario.matricula}} </td>
                            <td>{{horario.nombre}} </td>
                            <td>{{horario.sala}} </td>
                            <td>{{horario.hora}} </td>
                            <td><a href="{% url 'edit_asistencia' horario.id %}">Update </a></td>
                            <td><a href="{% url 'delete_asistencia' horario.id %}">Delete</a></td>
                        </tr>
                        {% endfor%}
                    </tbody>
                </table>
                {% include side_down.html %}
                <!-- <a type="button" href="{% url 'create_asistencia' %}" class="btn btn-secondary">Crear</a>
                            </div>
                            
                
                        </div>
                        
                
                    </div>
                    
                    {# JS y jQuery Bootstrap #}
                    {% bootstrap_javascript jquery='full' %}
                </body>
                
                </html> -->

horario_sala/templates/create.html
{% extends "side_up.html" %}

{% block content %}


{% load widget_tweaks %}

<div class="container">
    <h1>Crear Registro </h1>
    <form method="post" novalidate>
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text
                }}</small>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Crear</button>
    </form>
</div>
{% endblock %}

horario_sala/templates/edit.html
{% extends "side_up.html" %}

{% block content %}


{% load widget_tweaks %}
<div class="container">
    <form method="POST" action="/update/{{horario.id}}">
        {% csrf_token %}
        <h3>Editar Valores </h3>
        <input type="text" hidden="true" name="id" value="{{ horario.id }}" class="form-control" />
        <br>

        <div class="form-group">
            <label for="exampleFormControlInput1">Matrícula:</label>
            <input type="text" class="form-control" placeholder="matrícula" name="matricula" id="id_matricula" required
                maxlength="50" value="{{ horario.matricula }}">
        </div>

        <div class="form-group">
            <label for="exampleFormControlInput1">Nombre:</label>
            <input type="text" class="form-control" placeholder="matrícula" name="nombre" id="id_nombre" required
                maxlength="50" value="{{ horario.nombre }}">
        </div>

        <div class="form-group">
            <label for="exampleFormControlInput1">Sala:</label>
            <input type="text" class="form-control" placeholder="matrícula" name="sala" id="id_sala" required
                maxlength="50" value="{{ horario.sala }}">
        </div>

        <div class="form-group">
            <label for="exampleFormControlInput1">Hora:</label>
            <input type="text" class="form-control" placeholder="matrícula" name="hora" id="id_hora" required
                maxlength="50" value="{{ horario.hora }}">
        </div>

        <button class="btn btn-outline-secondary" type="submit">Enviar </button>

    </form>
</div>
{% endblock %}

horario_sala/templates/home.html
{% extends "side_up.html" %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container py-4">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card" style="width: 18rem;">
                        <img src="http://www.unsis.edu.mx/laboratorios/images/labs_informatica/Lab_Inf1_tb.jpg"
                            class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Laboratorio de Tecnologías web</p>
                        </div>
                    </div>

                    <div class="card-body">
                        <p class="card-text">El Laboratorio de tecnologías, cuenta con un área física de 6.00 x 4.00
                            mts. Este laboratorio dispone de diversos recursos que apoyan al 15% del total de materias
                            del Plan de Estudios de la Licenciatura en Informática..</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card" style="width: 18rem;">
                        <img src="http://www.unsis.edu.mx/laboratorios/images/labs_informatica/Lab_Inf2_tb.jpg"
                            class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Laboratorio de Redes</p>
                        </div>
                    </div>

                    <div class="card-body">
                        <p class="card-text">El Laboratorio de Redes, cuenta con un área física de 6.00 x 4.00 mts. Este
                            laboratorio dispone de diversos recursos que apoyan al 15% del total de materias del Plan de
                            Estudios de la Licenciatura en Informática.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card" style="width: 18rem;">
                        <img src="http://www.unsis.edu.mx/laboratorios/images/labs_informatica/Lab_Inf3_tb.jpg"
                            class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Laboratorio de IHC</p>
                        </div>
                    </div>

                    <div class="card-body">
                        <p class="card-text">El Laboratorio de IHC, cuenta con un área física de 6.00 x 4.00 mts. Este
                            laboratorio dispone de diversos recursos que apoyan al 15% del total de materias del Plan de
                            Estudios de la Licenciatura en Informática.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card" style="width: 18rem;">
                        <img src="http://www.unsis.edu.mx/laboratorios/images/labs_informatica/Lab_Inf4_tb.jpg"
                            class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Laboratorio de Sistemas Digitales</p>
                        </div>
                    </div>

                    <div class="card-body">
                        <p class="card-text">Laboratorio de Sistemas digitales</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card" style="width: 18rem;">
                        <img src="http://www.unsis.edu.mx/laboratorios/images/labs_informatica/Lab_Inf5_tb.jpg"
                            class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Laboratorio de Sistemas Operativos</p>
                        </div>
                    </div>

                    <div class="card-body">
                        <p class="card-text">Laboratorio de Sistemas Operativos</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card" style="width: 18rem;">
                        <img src="http://www.unsis.edu.mx/laboratorios/images/labs_informatica/Lab_Inf7_tb.jpg"
                            class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text">Laboratorio de Software</p>
                        </div>
                    </div>

                    <div class="card-body">
                        <p class="card-text">Laboratorio de Software</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>
{% endblock %}

horario_sala/templates/index.html
{% extends "side_up.html" %}

{% block content %}

<div class="container">
    <h1>Tabla de contenido</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Matricula</th>
                <th scope="col">Nombre</th>
                <th scope="col">Sala</th>
                <th scope="col">Hora </th>
                <th scope="col">Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for horario in lista_horarios_sala %}
            <tr>
                <td>{{horario.id}} </td>
                <td>{{horario.matricula}} </td>
                <td>{{horario.nombre}} </td>
                <td>{{horario.sala}} </td>
                <td>{{horario.hora}} </td>
                <td>
                    <a class="btn btn-outline-secondary" href="{% url 'edit_asistencia' horario.id %}">Actualizar </a>
                    <a class="btn btn-outline-secondary" href="{% url 'delete_asistencia' horario.id %}">Eliminar </a>
                </td>
            </tr>
            {% endfor%}
        </tbody>
    </table>
</div>
{% endblock %}

horario_sala/templates/side_up.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TecInfoII</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    {# Cargamos la librería #}
    {% load bootstrap4 %}

    {# CSS Bootstrap #}
    {% bootstrap_css %}

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav sidebar sidebar-dark accordion" id="accordionSidebar" style="background-color:#B22222;">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'index' %}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">INFORMÁTICA</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>CETI</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Asistencia CETI
            </div>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">
                    <i class="fas fa-fw fa-home"></i>
                    <span>Inicio</span></a>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create_asistencia' %}">
                    <i class="fas fa-fw fa-check-circle"></i>
                    <span>Crear</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">
                    <i class="fas fa-fw fa-bars"></i>
                    <span>Listar</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">
                    <i class="fas fa-fw fa-bars"></i>
                    <span>Acerca de</span></a>
            </li>
        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content" class="container py-4">
                {% block content %}

                {% endblock %}

            </div>
            <!-- End of Main Content -->
            <footer class="text-muted py-5" style="background-color:#B22222;">
                <div class="container">
                    <p class="float-end mb-1">
                        <a href="{% url 'index' %}">Inicio</a>
                    </p>
                    <p class="mb-1">UNSIS &copy; Unversidad de la Sierra Sur</p>
                    <p class="mb-0">UNSIS <a href="http://www.unsis.edu.mx/">Calle Guillermo Rojas Mijangos S/N, Esq.
                            Av. Universidad Col. Ciudad Universitaria, Miahuatlán de Porfirio Díaz, Oax., México C.P.
                            70800</a> </p>
                </div>
            </footer>
        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    {# JS y jQuery Bootstrap #}
    {% bootstrap_javascript jquery='full' %}
</body>

</html>